name: Bitbucket Checkout Workflow

on:
  workflow_dispatch:

jobs:
  checkout:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code from Bitbucket
        uses: choreo-templates/bitbucket-checkout@v0.2.0
        with:
          token: "BBDC-Njc1MTQ2NzY4NDY3OrNbWanSuCFKZNBI86WJW9no5daQ"
          serverUrl: "https://6f4f-203-94-95-3.ngrok-free.app"
          userOrgName: "tes"
          userRepoName: "test-repo-public"
          configRepoName: "TestDev"
          branch: "main"
          commitUser: "choreo-bot"
          commitEmail: "hansijk@yahoo.com"
