name: Checkout Bitbucket Server Repository

on:
  workflow_dispatch:

jobs:
  checkout:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Add Bitbucket Remote Origin
      run: |
        git config --global user.name hansijk
        # git config --global http.extraHeader "Authorization: Bearer BBDC-MjQwMzk0MTQ1MTg3Ojl/SsR2GMSaaQqwFQbVDZDIwNxP"
        # git remote set-url origin https://aae7-203-94-95-3.ngrok-free.app/scm/tes/testrepo.git
        git remote set-url origin https://username:BBDC-MjQwMzk0MTQ1MTg3Ojl/SsR2GMSaaQqwFQbVDZDIwNxP@aae7-203-94-95-3.ngrok-free.app/scm/tes/testrepo.git
        git fetch origin

    - name: Verify remote origin
      run: |
        git remote -v
