name: Checkout Bitbucket Server Repository

on:
  workflow_dispatch:

jobs:
  checkout:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Add Bitbucket Remote Origin
      run: |
        git config --global user.name hansijk
        git config http.extraHeader "Authorization: Bearer BBDC-NDY2MjI5NzM2Mjk4OgFKGMbWu5s9QhBIEluapEoRRjEK"
        git remote set-url origin https://aae7-203-94-95-3.ngrok-free.app/scm/tes/testrepo.git
        git fetch origin

    - name: Verify remote origin
      run: |
        git remote -v
