name: Checkout Bitbucket Server Repository

on:
  workflow_dispatch:
    inputs:
      repository-url:
        description: 'Bitbucket repository URL'
        required: false

jobs:
  checkout:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Add Bitbucket Remote Origin
      run: |
        git config --global user.name hansijk
        git config http.extraHeader "Authorization: Bearer BBDC-Njc1MTQ2NzY4NDY3OrNbWanSuCFKZNBI86WJW9no5daQ"
        git remote set-url origin ${{ github.event.inputs.repository-url }}
        git fetch origin

    - name: Verify remote origin
      run: |
        git remote -v
