name: Checkout Bitbucket Server Repository

on:
  workflow_dispatch:

jobs:
  checkout:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Clone Bitbucket repository
      run: |
        git config --global user.name hansijk
        git config --global http.extraHeader "Authorization: Bearer BBDC-MjQwMzk0MTQ1MTg3Ojl/SsR2GMSaaQqwFQbVDZDIwNxP"
        git remote add origin https://aae7-203-94-95-3.ngrok-free.app/scm/tes/testrepo.git

    - name: Display repository content
      run: ls bitbucket-repo
